const weatherCodeDescriptions = {
  0: { description: "Clear", niceDay: true, color: "#CDD2D8" },
  1: { description: "Mostly Clear", niceDay: true, color: "#CDD2D8" },
  2: { description: "Partly Cloudy", niceDay: true, color: "#CDD2D8" },
  3: { description: "Cloudy", niceDay: false, color: "#9BA6B1" },
  45: { description: "Fog", niceDay: false, color: "#9BA6B1" },
  48: { description: "Freezing Fog", niceDay: false, color: "#9BA6B1" },
  51: { description: "Light Drizzle", niceDay: false, color: "#9BA6B1" },
  53: { description: "Drizzle", niceDay: false, color: "#506376" },
  55: { description: "Heavy Drizzle", niceDay: false, color: "#506376" },
  56: {
    description: "Light Freezing Drizzle",
    niceDay: false,
    color: "#9BA6B1",
  },
  57: { description: "Freezing Drizzle", niceDay: false, color: "#506376" },
  61: { description: "Light Rain", niceDay: false, color: "#506376" },
  63: { description: "Rain", niceDay: false, color: "#929FC9" },
  65: { description: "Heavy Rain", niceDay: false, color: "#929FC9" },
  66: { description: "Light Freezing Rain", niceDay: false, color: "#929FC9" },
  67: { description: "Freezing Rain", niceDay: false, color: "#929FC9" },
  71: { description: "Light Snow", niceDay: false, color: "#05213C" },
  73: { description: "Snow", niceDay: false, color: "#05213C" },
  75: { description: "Heavy Snow", niceDay: false, color: "#05213C" },
  77: { description: "Snow Grains", niceDay: false, color: "#05213C" },
  80: { description: "Light Rain Shower", niceDay: false, color: "#929FC9" },
  81: { description: "Rain Shower", niceDay: false, color: "#929FC9" },
  82: { description: "Heavy Rain Shower", niceDay: false, color: "#929FC9" },
  85: { description: "Snow Shower", niceDay: false, color: "#05213C" },
  86: { description: "Heavy Snow Shower", niceDay: false, color: "#05213C" },
  95: { description: "Thunderstorm", niceDay: false, color: "#929FC9" },
  96: { description: "Hailstorm", niceDay: false, color: "#929FC9" },
  99: { description: "Heavy Hailstorm", niceDay: false, color: "#929FC9" },
};

export default weatherCodeDescriptions;
